// Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.
namespace CuteAnt.Text.RegularExpressions
{
  internal class SR : CuteAnt.Text.RegularExpressions.Strings
  {
    private SR()
    {
    }
    internal static string Format(string resourceFormat, params object[] args)
    {
      if (args != null)
      {
        return string.Format(resourceFormat, args);
      }

      return resourceFormat;
    }

    internal static string Format(string resourceFormat, object p1)
    {
      return string.Format(resourceFormat, p1);
    }

    internal static string Format(string resourceFormat, object p1, object p2)
    {
      return string.Format(resourceFormat, p1, p2);
    }

    internal static string Format(string resourceFormat, object p1, object p2, object p3)
    {
      return string.Format(resourceFormat, p1, p2, p3);
    }
  }
}
