//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.JsonPatch {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonPatchSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonPatchSR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.JsonPatch.JsonPatchSR", typeof(JsonPatchSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The property at &apos;{0}&apos; could not be copied. 的本地化字符串。
        /// </summary>
        internal static string CannotCopyProperty {
            get {
                return ResourceManager.GetString("CannotCopyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the property at path &apos;{0}&apos; could not be determined. 的本地化字符串。
        /// </summary>
        internal static string CannotDeterminePropertyType {
            get {
                return ResourceManager.GetString("CannotDeterminePropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; operation at path &apos;{1}&apos; could not be performed. 的本地化字符串。
        /// </summary>
        internal static string CannotPerformOperation {
            get {
                return ResourceManager.GetString("CannotPerformOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property at &apos;{0}&apos; could not be read. 的本地化字符串。
        /// </summary>
        internal static string CannotReadProperty {
            get {
                return ResourceManager.GetString("CannotReadProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property at path &apos;{0}&apos; could not be updated. 的本地化字符串。
        /// </summary>
        internal static string CannotUpdateProperty {
            get {
                return ResourceManager.GetString("CannotUpdateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expression &apos;{0}&apos; is not supported. Supported expressions include member access and indexer expressions. 的本地化字符串。
        /// </summary>
        internal static string ExpressionTypeNotSupported {
            get {
                return ResourceManager.GetString("ExpressionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The index value provided by path segment &apos;{0}&apos; is out of bounds of the array size. 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfBounds {
            get {
                return ResourceManager.GetString("IndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path segment &apos;{0}&apos; is invalid for an array index. 的本地化字符串。
        /// </summary>
        internal static string InvalidIndexValue {
            get {
                return ResourceManager.GetString("InvalidIndexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The JSON patch document was malformed and could not be parsed. 的本地化字符串。
        /// </summary>
        internal static string InvalidJsonPatchDocument {
            get {
                return ResourceManager.GetString("InvalidJsonPatchDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid JsonPatch operation &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidJsonPatchOperation {
            get {
                return ResourceManager.GetString("InvalidJsonPatchOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided path segment &apos;{0}&apos; cannot be converted to the target type. 的本地化字符串。
        /// </summary>
        internal static string InvalidPathSegment {
            get {
                return ResourceManager.GetString("InvalidPathSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided string &apos;{0}&apos; is an invalid path. 的本地化字符串。
        /// </summary>
        internal static string InvalidValueForPath {
            get {
                return ResourceManager.GetString("InvalidValueForPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is invalid for target location. 的本地化字符串。
        /// </summary>
        internal static string InvalidValueForProperty {
            get {
                return ResourceManager.GetString("InvalidValueForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ParameterMustMatchType {
            get {
                return ResourceManager.GetString("ParameterMustMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; which is an array is not supported for json patch operations as it has a fixed size. 的本地化字符串。
        /// </summary>
        internal static string PatchNotSupportedForArrays {
            get {
                return ResourceManager.GetString("PatchNotSupportedForArrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; which is a non generic list is not supported for json patch operations. Only generic list types are supported. 的本地化字符串。
        /// </summary>
        internal static string PatchNotSupportedForNonGenericLists {
            get {
                return ResourceManager.GetString("PatchNotSupportedForNonGenericLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target location specified by path segment &apos;{0}&apos; was not found. 的本地化字符串。
        /// </summary>
        internal static string TargetLocationAtPathSegmentNotFound {
            get {
                return ResourceManager.GetString("TargetLocationAtPathSegmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For operation &apos;{0}&apos;, the target location specified by path &apos;{1}&apos; was not found. 的本地化字符串。
        /// </summary>
        internal static string TargetLocationNotFound {
            get {
                return ResourceManager.GetString("TargetLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The test operation is not supported. 的本地化字符串。
        /// </summary>
        internal static string TestOperationNotSupported {
            get {
                return ResourceManager.GetString("TestOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current value &apos;{0}&apos; at position &apos;{2}&apos; is not equal to the test value &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ValueAtListPositionNotEqualToTestValue {
            get {
                return ResourceManager.GetString("ValueAtListPositionNotEqualToTestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value at &apos;{0}&apos; cannot be null or empty to perform the test operation. 的本地化字符串。
        /// </summary>
        internal static string ValueForTargetSegmentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ValueForTargetSegmentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current value &apos;{0}&apos; at path &apos;{2}&apos; is not equal to the test value &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ValueNotEqualToTestValue {
            get {
                return ResourceManager.GetString("ValueNotEqualToTestValue", resourceCulture);
            }
        }
    }
}
