// Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.
using System.Globalization;

namespace System.Reflection
{
  internal class SR : System.Reflection.Strings
  {
    private SR()
    {
    }
    internal static string Format(string formatStr, params object[] args)
    {
      return string.Format(CultureInfo.CurrentCulture, formatStr, args);
    }
  }
}
