//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Reflection {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Reflection.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly already added. 的本地化字符串。
        /// </summary>
        internal static string AssemblyAlreadyAdded {
            get {
                return ResourceManager.GetString("AssemblyAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base reader must be a full metadata reader. 的本地化字符串。
        /// </summary>
        internal static string BaseReaderMustBeFullMetadataReader {
            get {
                return ResourceManager.GetString("BaseReaderMustBeFullMetadataReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blob is to large. 的本地化字符串。
        /// </summary>
        internal static string BlobTooLarge {
            get {
                return ResourceManager.GetString("BlobTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation is not valid on this builder as it has been linked with another one. 的本地化字符串。
        /// </summary>
        internal static string BuilderAlreadyLinked {
            get {
                return ResourceManager.GetString("BuilderAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Builder must be aligned to 4 byte boundary. 的本地化字符串。
        /// </summary>
        internal static string BuilderMustAligned {
            get {
                return ResourceManager.GetString("BuilderMustAligned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t get a heap offset for a virtual heap handle 的本地化字符串。
        /// </summary>
        internal static string CantGetOffsetForVirtualHeapHandle {
            get {
                return ResourceManager.GetString("CantGetOffsetForVirtualHeapHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t emit a branch or exception region, the current encoder not created with a control flow builder. 的本地化字符串。
        /// </summary>
        internal static string ControlFlowBuilderNotAvailable {
            get {
                return ResourceManager.GetString("ControlFlowBuilderNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data too big to fit in memory. 的本地化字符串。
        /// </summary>
        internal static string DataTooBig {
            get {
                return ResourceManager.GetString("DataTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The distance between the instruction {0} (offset {1}) and the target label doesn&apos;t fit the operand size: {2} 的本地化字符串。
        /// </summary>
        internal static string DistanceBetweenInstructionAndLabelTooBig {
            get {
                return ResourceManager.GetString("DistanceBetweenInstructionAndLabelTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnCMap table not sorted or has missing records. 的本地化字符串。
        /// </summary>
        internal static string EnCMapNotSorted {
            get {
                return ResourceManager.GetString("EnCMapNotSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected array of size {0}. 的本地化字符串。
        /// </summary>
        internal static string ExpectedArrayOfSize {
            get {
                return ResourceManager.GetString("ExpectedArrayOfSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected list of size {0}. 的本地化字符串。
        /// </summary>
        internal static string ExpectedListOfSize {
            get {
                return ResourceManager.GetString("ExpectedListOfSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected non-empty list. 的本地化字符串。
        /// </summary>
        internal static string ExpectedNonEmptyList {
            get {
                return ResourceManager.GetString("ExpectedNonEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected non-empty string. 的本地化字符串。
        /// </summary>
        internal static string ExpectedNonEmptyString {
            get {
                return ResourceManager.GetString("ExpectedNonEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle belongs to a future generation 的本地化字符串。
        /// </summary>
        internal static string HandleBelongsToFutureGeneration {
            get {
                return ResourceManager.GetString("HandleBelongsToFutureGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash must be at least {0}B long. 的本地化字符串。
        /// </summary>
        internal static string HashTooShort {
            get {
                return ResourceManager.GetString("HashTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The limit on the size of {0} heap has been exceeded. 的本地化字符串。
        /// </summary>
        internal static string HeapSizeLimitExceeded {
            get {
                return ResourceManager.GetString("HeapSizeLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illegal tables in compressed metadata stream. 的本地化字符串。
        /// </summary>
        internal static string IllegalTablesInCompressedMetadataStream {
            get {
                return ResourceManager.GetString("IllegalTablesInCompressedMetadataStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image is too small. 的本地化字符串。
        /// </summary>
        internal static string ImageTooSmall {
            get {
                return ResourceManager.GetString("ImageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image is either too small or contains an invalid byte offset or count. 的本地化字符串。
        /// </summary>
        internal static string ImageTooSmallOrContainsInvalidOffsetOrCount {
            get {
                return ResourceManager.GetString("ImageTooSmallOrContainsInvalidOffsetOrCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid coded index. 的本地化字符串。
        /// </summary>
        internal static string InvalidCodedIndex {
            get {
                return ResourceManager.GetString("InvalidCodedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid compressed integer. 的本地化字符串。
        /// </summary>
        internal static string InvalidCompressedInteger {
            get {
                return ResourceManager.GetString("InvalidCompressedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid constant value. 的本地化字符串。
        /// </summary>
        internal static string InvalidConstantValue {
            get {
                return ResourceManager.GetString("InvalidConstantValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of type &apos;{0}&apos; is not a constant. 的本地化字符串。
        /// </summary>
        internal static string InvalidConstantValueOfType {
            get {
                return ResourceManager.GetString("InvalidConstantValueOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid COR header size. 的本地化字符串。
        /// </summary>
        internal static string InvalidCorHeaderSize {
            get {
                return ResourceManager.GetString("InvalidCorHeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of field Characteristics in debug directory entry must be zero. 的本地化字符串。
        /// </summary>
        internal static string InvalidDebugDirectoryEntryCharacteristics {
            get {
                return ResourceManager.GetString("InvalidDebugDirectoryEntryCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid directory relative virtual address. 的本地化字符串。
        /// </summary>
        internal static string InvalidDirectoryRVA {
            get {
                return ResourceManager.GetString("InvalidDirectoryRVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid directory size. 的本地化字符串。
        /// </summary>
        internal static string InvalidDirectorySize {
            get {
                return ResourceManager.GetString("InvalidDirectorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid document name. 的本地化字符串。
        /// </summary>
        internal static string InvalidDocumentName {
            get {
                return ResourceManager.GetString("InvalidDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid entry point token: 0x{0:8X} 的本地化字符串。
        /// </summary>
        internal static string InvalidEntryPointToken {
            get {
                return ResourceManager.GetString("InvalidEntryPointToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid exception region bounds: start offset ({0}) is greater than end offset ({1}). 的本地化字符串。
        /// </summary>
        internal static string InvalidExceptionRegionBounds {
            get {
                return ResourceManager.GetString("InvalidExceptionRegionBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid handle. 的本地化字符串。
        /// </summary>
        internal static string InvalidHandle {
            get {
                return ResourceManager.GetString("InvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid import definition kind: {0}. 的本地化字符串。
        /// </summary>
        internal static string InvalidImportDefinitionKind {
            get {
                return ResourceManager.GetString("InvalidImportDefinitionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid local signature token: 0x{0:X8} 的本地化字符串。
        /// </summary>
        internal static string InvalidLocalSignatureToken {
            get {
                return ResourceManager.GetString("InvalidLocalSignatureToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid metadata section span. 的本地化字符串。
        /// </summary>
        internal static string InvalidMetadataSectionSpan {
            get {
                return ResourceManager.GetString("InvalidMetadataSectionSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Metadata stream format. 的本地化字符串。
        /// </summary>
        internal static string InvalidMetadataStreamFormat {
            get {
                return ResourceManager.GetString("InvalidMetadataStreamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid method header: 0x{0:X2} 的本地化字符串。
        /// </summary>
        internal static string InvalidMethodHeader1 {
            get {
                return ResourceManager.GetString("InvalidMethodHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid method header: 0x{0:X2} 0x{1:X2} 的本地化字符串。
        /// </summary>
        internal static string InvalidMethodHeader2 {
            get {
                return ResourceManager.GetString("InvalidMethodHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid relative virtual address (RVA): 0x{0:X8} 的本地化字符串。
        /// </summary>
        internal static string InvalidMethodRva {
            get {
                return ResourceManager.GetString("InvalidMethodRva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number of sections in declared in PE header. 的本地化字符串。
        /// </summary>
        internal static string InvalidNumberOfSections {
            get {
                return ResourceManager.GetString("InvalidNumberOfSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PE signature. 的本地化字符串。
        /// </summary>
        internal static string InvalidPESignature {
            get {
                return ResourceManager.GetString("InvalidPESignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid row count: {0} 的本地化字符串。
        /// </summary>
        internal static string InvalidRowCount {
            get {
                return ResourceManager.GetString("InvalidRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid SEH header: 0x{0:X2} 的本地化字符串。
        /// </summary>
        internal static string InvalidSehHeader {
            get {
                return ResourceManager.GetString("InvalidSehHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid serialized string. 的本地化字符串。
        /// </summary>
        internal static string InvalidSerializedString {
            get {
                return ResourceManager.GetString("InvalidSerializedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid signature. 的本地化字符串。
        /// </summary>
        internal static string InvalidSignature {
            get {
                return ResourceManager.GetString("InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid token. 的本地化字符串。
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type size. 的本地化字符串。
        /// </summary>
        internal static string InvalidTypeSize {
            get {
                return ResourceManager.GetString("InvalidTypeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified label doesn&apos;t belong to the current builder. 的本地化字符串。
        /// </summary>
        internal static string LabelDoesntBelongToBuilder {
            get {
                return ResourceManager.GetString("LabelDoesntBelongToBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label {0} has not been marked. 的本地化字符串。
        /// </summary>
        internal static string LabelNotMarked {
            get {
                return ResourceManager.GetString("LabelNotMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata header too small. 的本地化字符串。
        /// </summary>
        internal static string MetadataHeaderTooSmall {
            get {
                return ResourceManager.GetString("MetadataHeaderTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata image doesn&apos;t represent an assembly. 的本地化字符串。
        /// </summary>
        internal static string MetadataImageDoesNotRepresentAnAssembly {
            get {
                return ResourceManager.GetString("MetadataImageDoesNotRepresentAnAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid COR20 header signature. 的本地化字符串。
        /// </summary>
        internal static string MetadataSignature {
            get {
                return ResourceManager.GetString("MetadataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The MetadataStringDecoder instance used to instantiate the Metadata reader must have a UTF8 encoding. 的本地化字符串。
        /// </summary>
        internal static string MetadataStringDecoderEncodingMustBeUtf8 {
            get {
                return ResourceManager.GetString("MetadataStringDecoderEncodingMustBeUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata table header too small. 的本地化字符串。
        /// </summary>
        internal static string MetadataTableHeaderTooSmall {
            get {
                return ResourceManager.GetString("MetadataTableHeaderTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata table {0} not sorted. 的本地化字符串。
        /// </summary>
        internal static string MetadataTableNotSorted {
            get {
                return ResourceManager.GetString("MetadataTableNotSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata tables too small. 的本地化字符串。
        /// </summary>
        internal static string MetadataTablesTooSmall {
            get {
                return ResourceManager.GetString("MetadataTablesTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata version too long. 的本地化字符串。
        /// </summary>
        internal static string MetadataVersionTooLong {
            get {
                return ResourceManager.GetString("MetadataVersionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method body was created with no exception regions. 的本地化字符串。
        /// </summary>
        internal static string MethodHasNoExceptionRegions {
            get {
                return ResourceManager.GetString("MethodHasNoExceptionRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing data directory. 的本地化字符串。
        /// </summary>
        internal static string MissingDataDirectory {
            get {
                return ResourceManager.GetString("MissingDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module already added. 的本地化字符串。
        /// </summary>
        internal static string ModuleAlreadyAdded {
            get {
                return ResourceManager.GetString("ModuleAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number of rows of Module table: {0}. 的本地化字符串。
        /// </summary>
        internal static string ModuleTableInvalidNumberOfRows {
            get {
                return ResourceManager.GetString("ModuleTableInvalidNumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must not return null. 的本地化字符串。
        /// </summary>
        internal static string MustNotReturnNull {
            get {
                return ResourceManager.GetString("MustNotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough space for Blob stream. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughSpaceForBlobStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForBlobStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough space for GUID stream. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughSpaceForGUIDStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForGUIDStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough space for Metadata stream. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughSpaceForMetadataStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForMetadataStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough space for stream header name. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughSpaceForStreamHeaderName {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForStreamHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough space for String stream. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughSpaceForStringStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForStringStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough space for version string. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughSpaceForVersionString {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified handle is not a valid metadata heap handle. 的本地化字符串。
        /// </summary>
        internal static string NotMetadataHeapHandle {
            get {
                return ResourceManager.GetString("NotMetadataHeapHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified handle is not a valid metadata table or UserString heap handle. 的本地化字符串。
        /// </summary>
        internal static string NotMetadataTableOrUserStringHandle {
            get {
                return ResourceManager.GetString("NotMetadataTableOrUserStringHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified handle is not a TypeDefinitionHandle or TypeRefererenceHandle. 的本地化字符串。
        /// </summary>
        internal static string NotTypeDefOrRefHandle {
            get {
                return ResourceManager.GetString("NotTypeDefOrRefHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified handle is not a TypeDefinitionHandle, TypeRefererenceHandle, or TypeSpecificationHandle. 的本地化字符串。
        /// </summary>
        internal static string NotTypeDefOrRefOrSpecHandle {
            get {
                return ResourceManager.GetString("NotTypeDefOrRefOrSpecHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read out of bounds. 的本地化字符串。
        /// </summary>
        internal static string OutOfBoundsRead {
            get {
                return ResourceManager.GetString("OutOfBoundsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write out of bounds. 的本地化字符串。
        /// </summary>
        internal static string OutOfBoundsWrite {
            get {
                return ResourceManager.GetString("OutOfBoundsWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PE image does not have metadata. 的本地化字符串。
        /// </summary>
        internal static string PEImageDoesNotHaveMetadata {
            get {
                return ResourceManager.GetString("PEImageDoesNotHaveMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PE image not available. 的本地化字符串。
        /// </summary>
        internal static string PEImageNotAvailable {
            get {
                return ResourceManager.GetString("PEImageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified readers must be minimal delta metadata readers. 的本地化字符串。
        /// </summary>
        internal static string ReadersMustBeDeltaReaders {
            get {
                return ResourceManager.GetString("ReadersMustBeDeltaReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The size of the builder returned by {0}.{1} is smaller than requested. 的本地化字符串。
        /// </summary>
        internal static string ReturnedBuilderSizeTooSmall {
            get {
                return ResourceManager.GetString("ReturnedBuilderSizeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row count must be zero for table #{0}. 的本地化字符串。
        /// </summary>
        internal static string RowCountMustBeZero {
            get {
                return ResourceManager.GetString("RowCountMustBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row count specified for table index {0} is out of allowed range. 的本地化字符串。
        /// </summary>
        internal static string RowCountOutOfRange {
            get {
                return ResourceManager.GetString("RowCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row ID or heap offset is too large. 的本地化字符串。
        /// </summary>
        internal static string RowIdOrHeapOffsetTooLarge {
            get {
                return ResourceManager.GetString("RowIdOrHeapOffsetTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Section too small. 的本地化字符串。
        /// </summary>
        internal static string SectionTooSmall {
            get {
                return ResourceManager.GetString("SectionTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence point value is out of range. 的本地化字符串。
        /// </summary>
        internal static string SequencePointValueOutOfRange {
            get {
                return ResourceManager.GetString("SequencePointValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t add vararg parameters to non-vararg signature. 的本地化字符串。
        /// </summary>
        internal static string SignatureNotVarArg {
            get {
                return ResourceManager.GetString("SignatureNotVarArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signature provider returned invalid signature. 的本地化字符串。
        /// </summary>
        internal static string SignatureProviderReturnedInvalidSignature {
            get {
                return ResourceManager.GetString("SignatureProviderReturnedInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signature type sequence must have at least one element. 的本地化字符串。
        /// </summary>
        internal static string SignatureTypeSequenceMustHaveAtLeastOneElement {
            get {
                return ResourceManager.GetString("SignatureTypeSequenceMustHaveAtLeastOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Declared size doesn&apos;t correspond to the actual size. 的本地化字符串。
        /// </summary>
        internal static string SizeMismatch {
            get {
                return ResourceManager.GetString("SizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standalone debug metadata image doesn&apos;t contain Module table. 的本地化字符串。
        /// </summary>
        internal static string StandaloneDebugMetadataImageDoesNotContainModuleTable {
            get {
                return ResourceManager.GetString("StandaloneDebugMetadataImageDoesNotContainModuleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream header too small. 的本地化字符串。
        /// </summary>
        internal static string StreamHeaderTooSmall {
            get {
                return ResourceManager.GetString("StreamHeaderTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream must support read and seek operations. 的本地化字符串。
        /// </summary>
        internal static string StreamMustSupportReadAndSeek {
            get {
                return ResourceManager.GetString("StreamMustSupportReadAndSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stream length minus starting position is too large to hold a PEImage. 的本地化字符串。
        /// </summary>
        internal static string StreamTooLarge {
            get {
                return ResourceManager.GetString("StreamTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table row count space to small. 的本地化字符串。
        /// </summary>
        internal static string TableRowCountSpaceTooSmall {
            get {
                return ResourceManager.GetString("TableRowCountSpaceTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are too many exception regions. 的本地化字符串。
        /// </summary>
        internal static string TooManyExceptionRegions {
            get {
                return ResourceManager.GetString("TooManyExceptionRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are too many subnamespaces. 的本地化字符串。
        /// </summary>
        internal static string TooManySubnamespaces {
            get {
                return ResourceManager.GetString("TooManySubnamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected array of length {0}. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedArrayLength {
            get {
                return ResourceManager.GetString("UnexpectedArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected CodeView data signature value. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedCodeViewDataSignature {
            get {
                return ResourceManager.GetString("UnexpectedCodeViewDataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Debug directory was not of type {0}. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedDebugDirectoryType {
            get {
                return ResourceManager.GetString("UnexpectedDebugDirectoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected Embedded Portable PDB data signature value. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEmbeddedPortablePdbDataSignature {
            get {
                return ResourceManager.GetString("UnexpectedEmbeddedPortablePdbDataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected handle kind: {0}. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedHandleKind {
            get {
                return ResourceManager.GetString("UnexpectedHandleKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected op-code: {0}. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedOpCode {
            get {
                return ResourceManager.GetString("UnexpectedOpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected signature header for &apos;{0}&apos;, but found &apos;{1}&apos; (0x{2:x2}). 的本地化字符串。
        /// </summary>
        internal static string UnexpectedSignatureHeader {
            get {
                return ResourceManager.GetString("UnexpectedSignatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected signature header for &apos;{0}&apos; or &apos;{1}&apos;, but found &apos;{2}&apos; (0x{3:x2}). 的本地化字符串。
        /// </summary>
        internal static string UnexpectedSignatureHeader2 {
            get {
                return ResourceManager.GetString("UnexpectedSignatureHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected SignatureTypeCode: (0x{0:x}). 的本地化字符串。
        /// </summary>
        internal static string UnexpectedSignatureTypeCode {
            get {
                return ResourceManager.GetString("UnexpectedSignatureTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected stream end. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedStreamEnd {
            get {
                return ResourceManager.GetString("UnexpectedStreamEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown file format. 的本地化字符串。
        /// </summary>
        internal static string UnknownFileFormat {
            get {
                return ResourceManager.GetString("UnknownFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown PE Magic value. 的本地化字符串。
        /// </summary>
        internal static string UnknownPEMagicValue {
            get {
                return ResourceManager.GetString("UnknownPEMagicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown section name: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnknownSectionName {
            get {
                return ResourceManager.GetString("UnknownSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown tables: 0x{0:x16}. 的本地化字符串。
        /// </summary>
        internal static string UnknownTables {
            get {
                return ResourceManager.GetString("UnknownTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported format version: {0} 的本地化字符串。
        /// </summary>
        internal static string UnsupportedFormatVersion {
            get {
                return ResourceManager.GetString("UnsupportedFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be multiple of {0}. 的本地化字符串。
        /// </summary>
        internal static string ValueMustBeMultiple {
            get {
                return ResourceManager.GetString("ValueMustBeMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value is too large. 的本地化字符串。
        /// </summary>
        internal static string ValueTooLarge {
            get {
                return ResourceManager.GetString("ValueTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing mscorlib reference in AssemblyRef table. 的本地化字符串。
        /// </summary>
        internal static string WinMDMissingMscorlibRef {
            get {
                return ResourceManager.GetString("WinMDMissingMscorlibRef", resourceCulture);
            }
        }
    }
}
